### ISSUE TITLE
pip dependency requirements version

### ISSUE THREAD

**Issue by wbbeyourself** [MohammadrezaPourreza/DTS-SQL#2]
Could you share your requirements.txt version, such as torch, transformers, flash-attn, cuda version and so on ?

**Comment by MohammadrezaPourreza** [comment]
Thank you so much for bringing this to our attention, I added the requirements.txt

**Comment by wbbeyourself** [comment]
I have encountered lots of trobules when installing the flash-attn, but finally get it done. 
Here I share my experience to help others:

Environment:
conda

- python 3.9
- cuda 12.1
- transformers==4.38.1
- torch==2.2.0 # conda install pytorch==2.2.0  pytorch-cuda=12.1 -c pytorch -c nvidia
- packaging

After the above libs are installed, then begin to install the flash-attn, or you'll get lots of error.
run `pip install --use-pep517 -U flash-attn --no-build-isolation`
This command will install the newest flash-attn version.
flash-attn==2.5.5

That's all.
